_target_: real_env.peripherals.iphone.iPhone

name: third_person_camera_1
server_endpoint: tcp://localhost:16700
# iphone_udid: 00008130-000A742008A1401C
iphone_udid: ""

camera_configs:
  main:
    type: rgb
    peertalk_port: 5555
    width: 960
    height: 720
    fps: 60
  ultrawide:
    type: rgb
    peertalk_port: 5556
    width: 960
    height: 720
    fps: 60
  # depth:
  #   type: depth
  #   peertalk_port: 5557
  #   width: 320
  #   height: 240
  #   fps: 30

camera_latency_s: 0.08
display_resolution_WH:
  - 320
  - 240
# display_resolution_WH: null
logger_endpoint: tcp://localhost:55557
